# Generated by Django 3.2.23 on 2024-01-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_general_delete_cafes_delete_cervezas_delete_cortes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columna1', models.CharField(max_length=255)),
                ('columna2', models.IntegerField()),
            ],
        ),
    ]
