# Generated by Django 3.2.23 on 2024-01-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_tumodelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TuModelo',
        ),
    ]
